# -*- coding: utf-8 -*-
"""Text_Classification_NN_TensorFlow.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mlPAv_33ba10sQ2eD_OfzFzlNIxSYxIx
"""

# Declare Packages

import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

import numpy as np
import matplotlib.pyplot as plt

# Download the dataset in train test split as tensors in a input/label format

trainData, testData = tfds.load(name = 'imdb_reviews', split = ['train', 'test'], batch_size = -1, as_supervised = True)

trainData

testData

# Seperate tupled data into features and labels

trainFeatures, trainLabels = tfds.as_numpy(trainData)
testFeatures, testLabels = tfds.as_numpy(testData)

trainFeatures, trainLabels

testFeatures, testLabels

len(trainFeatures), len(trainLabels)

len(testFeatures), len(testLabels)

trainFeatures

trainLabels

testFeatures

testLabels

# Numerical Encoding of Movie Reviews Using Sentence Embedding

model = 'https://tfhub.dev/google/nnlm-en-dim50/2' # Found from the TensorFlow docs
encoding_layer = hub.KerasLayer(model, input_shape = [], dtype = tf.string, trainable = True)

# encoding_layer(trainFeatures[:5])

# Create the Validation Set for Tuning of the Model

X_validation = trainFeatures[:10000]
X_train = trainFeatures[10000:]

y_validation = trainLabels[:10000]
y_train = trainLabels[10000:]

X_train

y_train

# Build the Neural Network

model = tf.keras.Sequential([
    encoding_layer,
    tf.keras.layers.Dense(16, activation = 'relu'),
    tf.keras.layers.Dense(1)                             
])

model.compile(loss = tf.keras.losses.BinaryCrossentropy(from_logits = True),
              optimizer = tf.keras.optimizers.Adam(),
              metrics = [tf.metrics.BinaryAccuracy(threshold = 0.0, name = 'Calculation Accuracy')])

model.fit(X_train, y_train, epochs = 40, batch_size = 512, validation_data = (X_validation, y_validation))

model.evaluate(testFeatures, testLabels) # This model performed with an accuracy of ~84%